services:
  minio:
    image: bitnami/minio:2024.7.26
    hostname: ${INTERNAL_SERVER_NAME}
    container_name: minio_service
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: 'https://${INTERNAL_SERVER_NAME}/minio/ui'
      MINIO_ENABLE_CONSOLE: 'yes'
      MINIO_CONSOLE_PORT_NUMBER: '9001'
      MINIO_SKIP_CLIENT: 'yes'
    volumes:
      - ./minio_data:/bitnami/minio/data
    expose:
      - "9000"
      - "9001"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx_service
    env_file: .env
    volumes:
      - ./nginx/conf.d:/etc/nginx/templates:ro
      - ./nginx/certs:/etc/nginx/certs
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - INTERNAL_SERVER_NAME=${INTERNAL_SERVER_NAME}
      - EXTERNAL_IP_ADDRESS=${EXTERNAL_IP_ADDRESS}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - minio
    restart: always